version: '3.9'

services:
  backend:
    build:
      context: .
    container_name: backend
    hostname: localhost
    ports:
      - 8080:8080
  frontend:
    build: ./frontend
    container_name: frontend
    hostname: localhost
    ports:
      - 8081:8080